# Generated by Django 4.0.6 on 2022-07-20 02:44

import base.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=base.service.change_name_file, verbose_name='Фото'),
        ),
    ]
