# Generated by Django 4.0.6 on 2022-07-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_workpost_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTags',
        ),
    ]
