# Generated by Django 4.0.6 on 2022-07-30 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0003_delete_mytags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='messages', to='portfolio.room'),
        ),
        migrations.CreateModel(
            name='NotifyMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notify', models.CharField(choices=[('NEW_FOLLOWER', 'NEW_FOLLOWER'), ('SET_RAITING', 'SET_RAITING'), ('NEW_LIKE', 'NEW_LIKE'), ('NEW_COMMENT', 'NEW_COMMENT')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('is_view', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_dist', to=settings.AUTH_USER_MODEL)),
                ('src_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_src', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
