# Generated by Django 4.0.6 on 2022-08-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_uploadfilecontainer'),
        ('portfolio', '0004_alter_message_room_notifymsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.workpost', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.ManyToManyField(blank=True, related_name='comments_res', related_query_name='comments_res', to='portfolio.comment', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='base.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raiting_project', related_query_name='raiting_project', to='portfolio.workpost', verbose_name='Проект'),
        ),
    ]
