# Generated by Django 4.0.6 on 2022-08-05 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0005_alter_comment_project_alter_comment_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raiting_project', related_query_name='raiting_project', to='portfolio.workpost', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raiting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
