# Generated by Django 4.0.5 on 2022-07-17 03:49

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Способность')),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'способность',
                'verbose_name_plural': 'Skils',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to='users', verbose_name='Картинка')),
                ('links', models.TextField(blank=True, verbose_name='Внешние источники в JSON')),
                ('photo_user', models.TextField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('resume', models.JSONField(default=base.models.Profile.init_resume, verbose_name='Для резюме')),
                ('my_ip', models.JSONField(default=base.models.Profile.init_my_ip, verbose_name='Мои ip')),
                ('type_app', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Портфолио')], null=True, verbose_name='Приложение')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram пользователя')),
                ('keyword', models.CharField(blank=True, max_length=10, verbose_name='Слово для активации')),
                ('last_token', models.TextField(blank=True, max_length=500, verbose_name='Токен чата')),
                ('myskils', models.ManyToManyField(blank=True, related_name='profile_myskils', to='base.myskils', verbose_name='Skils')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профиль',
                'unique_together': {('user', 'type_app')},
            },
        ),
    ]
