# Generated by Django 4.0.6 on 2022-07-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='По желанию (нужно для переминование картинки)', max_length=200, verbose_name='Название фото')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='Фото')),
                ('link', models.TextField(blank=True, verbose_name='Внешняя ссылка')),
            ],
            options={
                'verbose_name': 'картинку',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
