# Generated by Django 4.0.6 on 2022-07-20 02:44

import base.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_imageslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslink',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=base.service.change_name_file, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=base.service.change_name_file, verbose_name='Картинка'),
        ),
    ]
