# Generated by Django 4.0.6 on 2022-07-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_uploadfilecontainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileContainer',
        ),
    ]
