# Generated by Django 4.0.6 on 2022-07-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='День')),
                ('month', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Месяц')),
                ('description', models.CharField(max_length=100, verbose_name='Праздник')),
                ('type_holiday', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж'), (3, 'Общий')], verbose_name='Чей праздник')),
            ],
            options={
                'verbose_name': 'праздник',
                'verbose_name_plural': 'Праздники',
                'unique_together': {('day', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=50, unique=True, verbose_name='Чат-ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Пользователь')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж')], null=True, verbose_name='Пол')),
                ('linkname', models.CharField(blank=True, max_length=50, verbose_name='Ссылка на пользователя')),
                ('day_user', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='День')),
                ('month_user', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Месяц')),
                ('content', models.TextField(blank=True, verbose_name='Шаблон ответа')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Время регистрации')),
                ('active', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TextHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Поздравление')),
                ('for_cont', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж'), (3, 'Общий')], null=True, verbose_name='Для кого контент')),
                ('holidays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_holidays', to='genie.holidays', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'поздравление',
                'verbose_name_plural': 'Поздравления',
            },
        ),
        migrations.CreateModel(
            name='PicsHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, verbose_name='Внешняя ссылка')),
                ('view', models.ImageField(blank=True, upload_to='', verbose_name='Фото к празднику')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='ИД фото')),
                ('for_cont', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж'), (3, 'Общий')], null=True, verbose_name='Для кого контент')),
                ('type_cont', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Фото'), (2, 'Стикер')], null=True, verbose_name='Тип контента')),
                ('holidays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pics_holidays', to='genie.holidays', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'картинку',
                'verbose_name_plural': 'Фото к празднику',
            },
        ),
        migrations.CreateModel(
            name='audioHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_audio', models.FileField(upload_to='', verbose_name='')),
                ('file_id', models.CharField(blank=True, max_length=200, verbose_name='ИД audio')),
                ('link', models.TextField(blank=True, verbose_name='Внешняя ссылка')),
                ('for_cont', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж'), (3, 'Общий')], null=True, verbose_name='Для кого контент')),
                ('holidays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_holidays', to='genie.holidays', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'музыку',
                'verbose_name_plural': 'Музыка',
            },
        ),
    ]
